db:
  host: localhost
  user: pgsu
  password: Qwerty123!
  database: TransactionService
  port: 5433
  
jwt:
  issuer: http://localhost:3000
  audience: TransactionService
  accessTokenLifetime: 900
  refreshTokenLifetime: 259200
  secret: MySuperSecretKey